import type { ToolPromptSpec } from "../types.js";

export const SKILL_TOOL_PROMPT_SPECS = [
  {
    id: "skill_search",
    contractId: "skill_search",
    neutralPurpose: "Find reusable team workflows by query.",
    neutralWhen: "Reusable guidance is needed and its skill name or id is unknown.",
    when: "A reusable team workflow may exist but its exact skill name is not known.",
    neutralContrasts: [
      { confusionEdgeId: "skill.search-vs-view-name", otherTool: "skill_view", cue: "Choose this when the name is unknown; choose name view for a known current-agent skill name." },
      { confusionEdgeId: "skill.search-vs-view-id", otherTool: "skill_view_by_id", cue: "Choose this to discover a skill id; choose id view when the id is already known." },
    ],
    responseHints: ["Matching team skill ids, names, and versions."],
  },
  {
    id: "skill_view",
    contractId: "skill_view",
    neutralPurpose: "Open a current-agent skill by name.",
    neutralWhen: "The current agent owns a skill with a known name and its content or manifest is needed.",
    when: "A skill owned by the current agent is known by name and must be opened to read its instructions and manifest.",
    neutralContrasts: [
      { confusionEdgeId: "skill.search-vs-view-name", otherTool: "skill_search", cue: "Choose this for a known current-agent name; choose search when the name is unknown." },
      { confusionEdgeId: "skill.view-name-vs-id", otherTool: "skill_view_by_id", cue: "Choose this for a current-agent name; choose id view for a skill id or team search result." },
    ],
    responseHints: ["Skill content, manifest, id, and version."],
  },
  {
    id: "skill_view_by_id",
    contractId: "skill_view_by_id",
    neutralPurpose: "Open a skill by exact id.",
    neutralWhen: "A skill id is known directly or from a team search result.",
    when: "A team skill returned by skill_search, or any skill known by exact skill_id, must be opened.",
    neutralContrasts: [
      { confusionEdgeId: "skill.search-vs-view-id", otherTool: "skill_search", cue: "Choose this when the id is known; choose search to discover a skill id." },
      { confusionEdgeId: "skill.view-name-vs-id", otherTool: "skill_view", cue: "Choose this for a skill id or team result; choose name view for a current-agent skill name." },
    ],
    responseHints: ["Skill content, manifest, id, and version."],
  },
  {
    id: "skill_files_read",
    contractId: "skill_files_read",
    neutralPurpose: "Read one skill resource into context.",
    neutralWhen: "A viewed manifest supplies a skill id and resource path whose content is needed in context.",
    neutralLimitations: "The skill id and path come from a viewed manifest.",
    when: "A specific resource path from a viewed skill manifest must be read into context.",
    avoid: "Do not guess skill ids or resource paths.",
    neutralContrasts: [
      { confusionEdgeId: "skill.file-read-vs-download", otherTool: "skill_files_download", cue: "Choose this for JSON-wrapped content in context; choose download for raw bytes written locally." },
    ],
    responseHints: ["JSON-wrapped resource content and encoding."],
  },
  {
    id: "skill_files_download",
    contractId: "skill_files_download",
    neutralPurpose: "Download one skill resource as raw bytes.",
    neutralWhen: "A viewed manifest supplies a skill id and path whose bytes are needed locally.",
    neutralLimitations: "The skill id and path come from a viewed manifest.",
    when: "A specific resource path from a viewed skill manifest must be downloaded as raw bytes.",
    avoid: "Do not guess skill ids or resource paths.",
    neutralContrasts: [
      { confusionEdgeId: "skill.file-read-vs-download", otherTool: "skill_files_read", cue: "Choose this for raw bytes written locally; choose file read for JSON-wrapped content in context." },
    ],
    responseHints: ["Raw resource bytes."],
  },
  {
    id: "skill_extract",
    contractId: "skill_extract",
    neutralPurpose: "Request skill extraction from the completed conversation.",
    neutralWhen: "The completed workflow is reusable and extraction capability is enabled.",
    when: "A completed conversation workflow is reusable and the current lifecycle capability allows forced archival.",
    responseHints: ["Extraction and archival status."],
  },
  {
    id: "skill_create",
    contractId: "skill_create",
    neutralPurpose: "Create a reusable skill.",
    neutralWhen: "A new reusable workflow needs a persisted skill and write capability is enabled.",
    when: "A new reusable skill must be persisted and write capability is enabled.",
    neutralContrasts: [
      { confusionEdgeId: "skill.create-vs-update", otherTool: "skill_update", cue: "Choose this for a new skill; choose update to replace the full body of an existing skill." },
    ],
    responseHints: ["Created skill id and version."],
  },
  {
    id: "skill_update",
    contractId: "skill_update",
    neutralPurpose: "Replace an existing skill's full body.",
    neutralWhen: "The complete body of an owned skill needs replacement at a known version.",
    when: "The complete SKILL.md body of an owned skill must be replaced.",
    neutralContrasts: [
      { confusionEdgeId: "skill.create-vs-update", otherTool: "skill_create", cue: "Choose this for an existing skill; choose create for a new skill." },
      { confusionEdgeId: "skill.update-vs-patch", otherTool: "skill_patch", cue: "Choose this for full-body replacement; choose patch for a bounded substring edit." },
    ],
    responseHints: ["Updated skill version."],
  },
  {
    id: "skill_patch",
    contractId: "skill_patch",
    neutralPurpose: "Edit a bounded substring in a skill body.",
    neutralWhen: "A known substring in an owned skill needs a narrow replacement at a known version.",
    when: "A narrow substring edit to an owned skill is safer than replacing the entire body.",
    neutralContrasts: [
      { confusionEdgeId: "skill.update-vs-patch", otherTool: "skill_update", cue: "Choose this for a bounded substring edit; choose update for full-body replacement." },
    ],
    responseHints: ["Patched skill version."],
  },
  {
    id: "skill_delete",
    contractId: "skill_delete",
    neutralPurpose: "Delete an owned skill and its versions.",
    neutralWhen: "An owned skill is selected for physical deletion at a known version.",
    when: "An owned skill and all of its versions must be physically deleted.",
    responseHints: ["Deletion status."],
  },
  {
    id: "skill_files_write",
    contractId: "skill_files_write",
    neutralPurpose: "Create or replace skill resource files.",
    neutralWhen: "Owned skill resources need creation or replacement at a known version.",
    when: "One or more resource files of an owned skill must be created or replaced.",
    neutralContrasts: [
      { confusionEdgeId: "skill.files-write-vs-remove", otherTool: "skill_files_remove", cue: "Choose this to create or replace files; choose files remove to delete resource paths." },
    ],
    responseHints: ["Updated skill version and file status."],
  },
  {
    id: "skill_files_remove",
    contractId: "skill_files_remove",
    neutralPurpose: "Remove skill resource files.",
    neutralWhen: "Owned skill resource paths need removal at a known version.",
    when: "One or more resource files of an owned skill must be removed.",
    neutralContrasts: [
      { confusionEdgeId: "skill.files-write-vs-remove", otherTool: "skill_files_write", cue: "Choose this to delete resource paths; choose files write to create or replace files." },
    ],
    responseHints: ["Updated skill version and removal status."],
  },
] as const satisfies readonly ToolPromptSpec[];
